=== chekanov/jas4pp/lcsim/tracking/src/main/resources/org/lcsim/recon/tracking/seedtracker/strategybuilder/strategies.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="StrategyList" type ="StrategyListType"/>

	<xsd:complexType name="StrategyListType"> 
		<xsd:sequence>
			<xsd:element name="TargetDetector" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Strategy" type="StrategyType" maxOccurs="unbounded"/>
		</xsd:sequence>

	</xsd:complexType>

	<xsd:complexType name = "StrategyType">
		<xsd:all>
			<xsd:element name="MinPT" type="xsd:double"/>
			<xsd:element name="MinHits" type="xsd:int"/>
			<xsd:element name="MinConfirm" type="xsd:int"/>
			<xsd:element name="MaxDCA" type="xsd:double"/>
			<xsd:element name="MaxZ0" type="xsd:double"/>
			<xsd:element name="MaxChisq" type="xsd:double"/>
			<xsd:element name="BadHitChisq" type="xsd:double"/>
                        <xsd:element name="Layers" type="LayersType"/>
                </xsd:all>
                <xsd:attribute name="name" type="xsd:string"/>	
	</xsd:complexType>

        
        <xsd:complexType name="LayersType">
            <xsd:sequence>
                <xsd:element name="Layer" type="LayerType" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
            
	<xsd:complexType name="LayerType">
		<xsd:attribute name="type" type="LayerCategory"/> 
		<xsd:attribute name="layer_number" type="xsd:int"/>
		<xsd:attribute name="detector_name" type="xsd:string"/>
		<xsd:attribute name="be_flag" type="BEFlag"/>
	</xsd:complexType>

	<xsd:simpleType name="LayerCategory">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Extend"/>
			<xsd:enumeration value="Confirm"/>
			<xsd:enumeration value="Seed"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="BEFlag">
		<xsd:restriction base="xsd:string">
				<xsd:enumeration value="BARREL"/>
				<xsd:enumeration value="ENDCAP_NORTH"/>
				<xsd:enumeration value="ENDCAP_SOUTH"/>
		</xsd:restriction>
	</xsd:simpleType>


</xsd:schema>

=== chekanov/jas4pp/lcsim/tracking/src/main/resources/org/lcsim/recon/tracking/seedtracker/strategies/autogen_qqbar500_sid02.xml
<?xml version="1.0" encoding="UTF-8"?>
<StrategyList xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="http://lcsim.org/recon/tracking/seedtracker/strategybuilder/strategies.xsd">
  <!--Strategy list Autogenerated by Strategy Builder on Tue Oct 14 18:52:22 PDT 2008.-->
  <TargetDetector>sid02</TargetDetector>
  <Strategy name="AUTOGEN0_-343517849">
    <!--AUTOGEN STATISTICS: 
			Score: 680.456618113855
			Unweighted Score (num new tracks): 84
			Adjacency: 39853.0
		-->
    <!--Cutoffs-->
    <MinPT>0.2</MinPT>
    <MinHits>7</MinHits>
    <MinConfirm>1</MinConfirm>
    <MaxDCA>10.0</MaxDCA>
    <MaxZ0>10.0</MaxZ0>
    <MaxChisq>50.0</MaxChisq>
    <BadHitChisq>15.0</BadHitChisq>
    <!--Layers-->
    <Layers>
      <Layer type="Seed" layer_number="2" detector_name="TrackerBarrel" be_flag="BARREL" />
      <Layer type="Seed" layer_number="1" detector_name="TrackerBarrel" be_flag="BARREL" />
      <Layer type="Seed" layer_number="0" detector_name="TrackerBarrel" be_flag="BARREL" />
      <Layer type="Confirm" layer_number="4" detector_name="VertexBarrel" be_flag="BARREL" />
      <Layer type="Extend" layer_number="4" detector_name="TrackerBarrel" be_flag="BARREL" />
      <Layer type="Extend" layer_number="3" detector_name="TrackerBarrel" be_flag="BARREL" />
      <Layer type="Extend" layer_number="3" detector_name="VertexBarrel" be_flag="BARREL" />
      <Layer type="Extend" layer_number="2" detector_name="VertexBarrel" be_flag="BARREL" />
      <Layer type="Extend" layer_number="1" detector_name="VertexBarrel" be_flag="BARREL" />
      <Layer type="Extend" layer_number="0" detector_name="VertexBarrel" be_flag="BARREL" />
      <Layer type="Extend" layer_number="0" detector_name="VertexEndcap" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="0" detector_name="VertexEndcap" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="1" detector_name="VertexEndcap" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="1" detector_name="VertexEndcap" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="1" detector_name="TrackerForward" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="1" detector_name="TrackerForward" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="2" detector_name="VertexEndcap" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="2" detector_name="VertexEndcap" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="0" detector_name="TrackerForward" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="0" detector_name="TrackerForward" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="3" detector_name="VertexEndcap" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="3" detector_name="VertexEndcap" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="0" detector_name="TrackerEndcap" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="0" detector_name="TrackerEndcap" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="1" detector_name="TrackerEndcap" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="1" detector_name="TrackerEndcap" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="2" detector_name="TrackerEndcap" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="2" detector_name="TrackerEndcap" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="3" detector_name="TrackerEndcap" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="3" detector_name="TrackerEndcap" be_flag="ENDCAP_SOUTH" />
    </Layers>
  </Strategy>
  <Strategy name="AUTOGEN2_2057828749">
    <!--AUTOGEN STATISTICS: 
			Score: 151.70428674375714
			Unweighted Score (num new tracks): 55
			Adjacency: 4.0
		-->
    <!--Cutoffs-->
    <MinPT>0.2</MinPT>
    <MinHits>7</MinHits>
    <MinConfirm>1</MinConfirm>
    <MaxDCA>10.0</MaxDCA>
    <MaxZ0>10.0</MaxZ0>
    <MaxChisq>50.0</MaxChisq>
    <BadHitChisq>15.0</BadHitChisq>
    <!--Layers-->
    <Layers>
      <Layer type="Seed" layer_number="0" detector_name="TrackerBarrel" be_flag="BARREL" />
      <Layer type="Seed" layer_number="3" detector_name="VertexBarrel" be_flag="BARREL" />
      <Layer type="Seed" layer_number="0" detector_name="VertexBarrel" be_flag="BARREL" />
      <Layer type="Confirm" layer_number="1" detector_name="VertexBarrel" be_flag="BARREL" />
      <Layer type="Extend" layer_number="4" detector_name="TrackerBarrel" be_flag="BARREL" />
      <Layer type="Extend" layer_number="3" detector_name="TrackerBarrel" be_flag="BARREL" />
      <Layer type="Extend" layer_number="2" detector_name="TrackerBarrel" be_flag="BARREL" />
      <Layer type="Extend" layer_number="1" detector_name="TrackerBarrel" be_flag="BARREL" />
      <Layer type="Extend" layer_number="4" detector_name="VertexBarrel" be_flag="BARREL" />
      <Layer type="Extend" layer_number="2" detector_name="VertexBarrel" be_flag="BARREL" />
      <Layer type="Extend" layer_number="0" detector_name="VertexEndcap" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="0" detector_name="VertexEndcap" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="1" detector_name="VertexEndcap" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="1" detector_name="VertexEndcap" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="1" detector_name="TrackerForward" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="1" detector_name="TrackerForward" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="2" detector_name="VertexEndcap" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="2" detector_name="VertexEndcap" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="0" detector_name="TrackerForward" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="0" detector_name="TrackerForward" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="3" detector_name="VertexEndcap" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="3" detector_name="VertexEndcap" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="0" detector_name="TrackerEndcap" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="0" detector_name="TrackerEndcap" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="1" detector_name="TrackerEndcap" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="1" detector_name="TrackerEndcap" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="2" detector_name="TrackerEndcap" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="2" detector_name="TrackerEndcap" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="3" detector_name="TrackerEndcap" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="3" detector_name="TrackerEndcap" be_flag="ENDCAP_SOUTH" />
    </Layers>
  </Strategy>
  <Strategy name="AUTOGEN3_-250068071">
    <!--AUTOGEN STATISTICS: 
			Score: 64639.73946189978
			Unweighted Score (num new tracks): 15734
			Adjacency: 9.0
		-->
    <!--Cutoffs-->
    <MinPT>0.2</MinPT>
    <MinHits>7</MinHits>
    <MinConfirm>1</MinConfirm>
    <MaxDCA>10.0</MaxDCA>
    <MaxZ0>10.0</MaxZ0>
    <MaxChisq>50.0</MaxChisq>
    <BadHitChisq>15.0</BadHitChisq>
    <!--Layers-->
    <Layers>
      <Layer type="Seed" layer_number="1" detector_name="TrackerBarrel" be_flag="BARREL" />
      <Layer type="Seed" layer_number="0" detector_name="TrackerBarrel" be_flag="BARREL" />
      <Layer type="Seed" layer_number="2" detector_name="VertexBarrel" be_flag="BARREL" />
      <Layer type="Confirm" layer_number="1" detector_name="VertexBarrel" be_flag="BARREL" />
      <Layer type="Extend" layer_number="4" detector_name="TrackerBarrel" be_flag="BARREL" />
      <Layer type="Extend" layer_number="3" detector_name="TrackerBarrel" be_flag="BARREL" />
      <Layer type="Extend" layer_number="2" detector_name="TrackerBarrel" be_flag="BARREL" />
      <Layer type="Extend" layer_number="4" detector_name="VertexBarrel" be_flag="BARREL" />
      <Layer type="Extend" layer_number="3" detector_name="VertexBarrel" be_flag="BARREL" />
      <Layer type="Extend" layer_number="0" detector_name="VertexBarrel" be_flag="BARREL" />
      <Layer type="Extend" layer_number="0" detector_name="VertexEndcap" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="0" detector_name="VertexEndcap" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="1" detector_name="VertexEndcap" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="1" detector_name="VertexEndcap" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="2" detector_name="VertexEndcap" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="2" detector_name="VertexEndcap" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="1" detector_name="TrackerForward" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="1" detector_name="TrackerForward" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="0" detector_name="TrackerForward" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="0" detector_name="TrackerForward" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="3" detector_name="VertexEndcap" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="3" detector_name="VertexEndcap" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="0" detector_name="TrackerEndcap" be_flag="ENDCAP_NORTH" />
      <Layer type="Extend" layer_number="0" detector_name="TrackerEndcap" be_flag="ENDCAP_SOUTH" />
      <Layer type="Extend" layer_number="1" detector_name="TrackerEndcap" be_flag="ENDCAP_NORTH" />
