=== chekanov/jas4pp/jas-base/extensions/TextImport/src/main/resources/org/freehep/jas/extensions/text/core/textmetadata.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT format EMPTY>
<!ATTLIST format
    name  CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT column (format)*>
<!ATTLIST column
   index CDATA #REQUIRED
    name CDATA #IMPLIED
    skip CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT columns (column)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT fixed (position)*>

<!ELEMENT position EMPTY>
<!ATTLIST position
   index CDATA #REQUIRED
  >


<!--- Put your DTDDoc comment here. -->
<!ELEMENT delimited (#PCDATA)>
<!ATTLIST delimited
    textQualifier CDATA #IMPLIED
    coalesceDelimiters CDATA #IMPLIED
    delimiters CDATA #IMPLIED
    tabIsDelimiter CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT options EMPTY>
<!ATTLIST options
    firstDataRow CDATA #IMPLIED
    columnHeaderRow CDATA #IMPLIED
    comment CDATA #IMPLIED
    previewRows CDATA #IMPLIED
    gzip CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT textmetadata (options?,(fixed|delimited),columns?)>

=== chekanov/jas4pp/jas-base/extensions/TextImport/src/main/resources/org/freehep/jas/extensions/text/gui/XMLDocument.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE textmetadata SYSTEM "http://java.freehep.org/schemas/textmetadata/1.0/textmetadata.dtd">

<textmetadata>
  <options gzip="false" previewLines="1000" comment="#" headerRow="1" firstDataRow="2"/> 
  <delimited delimiters=" " coalesceDelimiters="true" textQualifier="'"/>
  <columns>
     <column index="1" skip="true" name="category">
       <format name="Integer" param="xyz"/>
     </column>
     <column index="2" skip="true" name="category">
       <format name="Integer" param="xyz"/>
     </column>
  </columns>   
</textmetadata>
