=== chekanov/jas4pp/lcsim/detector-framework/src/main/resources/org/lcsim/schemas/compact/1.0/compact.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE  xs:schema >
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="unqualified"
           version="1.0"
           xmlns:compact="http://www.lcsim.org/schemas/compact/1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="info">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="comment" type="xs:string" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="title" type="xs:string" use="optional" />
            <xs:attribute name="author" type="xs:string" use="optional" />
            <xs:attribute name="url" type="xs:anyURI" use="optional"/>
            <xs:attribute name="version" type="xs:string" use="optional" />
            <xs:attribute name="status" default="development">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="deprecated" />
                        <xs:enumeration value="production" />
                        <xs:enumeration value="development" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="define">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="constant" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attribute name="name" type="xs:string" use="required"/>
                            <xs:attribute name="value" type="xs:string" use="required"/>
                        </xs:complexType>                    
                    </xs:element>
                    <xs:element name="matrix" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attribute name="name" type="xs:string" use="required" />
                            <xs:attribute name="coldim" type="xs:integer" use="required" />
                            <xs:attribute name="values" type="xs:string" use="required" />
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="limits">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="limitset" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="limit" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="name" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="step_length_max" />
                                                <xs:enumeration value="track_length_max" />
                                                <xs:enumeration value="time_max" />
                                                <xs:enumeration value="ekin_min" />
                                                <xs:enumeration value="range_min" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="particles" type="xs:string"/>
                                    <xs:attribute name="value" type="xs:double"/>
                                    <xs:attribute name="unit" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="regions">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="region" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="storeSecondaries" type="xs:boolean" default="false"/>
                        <xs:attribute name="killTracks" type="xs:boolean" default="false"/>
                        <xs:attribute name="cut" type="xs:double" default="1.0" />
                        <xs:attribute name="lunit" type="xs:string" default="mm"/>
                        <xs:attribute name="threshold" type="xs:double" default="0.0"/>
                        <xs:attribute name="eunit" type="xs:string" default="MeV"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="materials">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="material" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="property" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="name" type="xs:string" use="required" />
                                    <xs:attribute name="ref" type="xs:string" use="required" />
                                </xs:complexType>
                            </xs:element>                            
                            <xs:element name="D" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="type" type="xs:string" default="density"/>
                                    <xs:attribute name="unit" type="xs:string" default="g/cm3" />
                                    <xs:attribute name="value" type="xs:double" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:choice>
                                <xs:element name="fraction" minOccurs="1" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:attribute name="n" type="xs:double" use="required"/>
                                        <xs:attribute name="ref" type="xs:string" use="required"/>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="composite" minOccurs="1" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:attribute name="n" type="xs:integer" use="required"/>
                                        <xs:attribute name="ref" type="xs:string" use="required"/>
                                    </xs:complexType>
                                </xs:element>
                            </xs:choice>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="display">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="vis" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required" />
                        <xs:attribute name="r" type=" xs:double " default="1.0" />
                        <xs:attribute name="g" type=" xs:double " default="1.0" />
                        <xs:attribute name="b" type=" xs:double " default="1.0" />
                        <xs:attribute name="alpha" type=" xs:double " default="1.0" />
                        <xs:attribute name="visible" type="xs:boolean" default="true"/>
                        <xs:attribute name="showDaughters" type="xs:boolean" default="true"/>
                        <xs:attribute name="lineStyle" default="unbroken">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="unbroken"/>
                                    <xs:enumeration value="dashed"/>
                                    <xs:enumeration value="dotted"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="drawingStyle" default="wireframe">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="wireframe"/>
                                    <xs:enumeration value="solid"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="detector">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="comment" minOccurs="0" maxOccurs="1" type="xs:string"/>
                <xs:element name="dimensions" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:anyAttribute processContents="lax" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="layer" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="slice" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="material" type="xs:string" use="required"/>
                                    <xs:attribute name="thickness" type="xs:string" use="required"/>
                                    <xs:attribute name="sensitive" default="no">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="yes" />
                                                <xs:enumeration value="no" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="region" type="xs:string" use="optional"/>
                                    <xs:attribute name="limits" type="xs:string" use="optional"/>
                                    <xs:attribute name="vis" type="xs:string" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
                        </xs:sequence>
                        <xs:anyAttribute processContents="lax"/> <!-- layer -->
                    </xs:complexType>
                </xs:element>
                <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax" />
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="type" type="xs:string" use="required"/>
            <xs:attribute name="id" type="xs:integer" use="optional" default="0"/>
            <xs:attribute name="readout" type="xs:string" use="optional" />
            <xs:attribute name="insideTrackingVolume" type="xs:boolean" use="optional" />
            <xs:attribute name="reflect" type="xs:boolean" use="optional"/>
            <xs:attribute name="combineHits" type="xs:boolean" use="optional"/>
            <xs:attribute name="calorimeterType" type="xs:string" use="optional"/>
            <xs:anyAttribute processContents="lax"/>
        </xs:complexType>
    </xs:element>                

    <xs:group name="detGroup">
        <xs:sequence>
            <xs:element name="comment" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
            <xs:element ref="detector" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:group>
    
    <xs:element name="detectors">
        <xs:complexType>
            <xs:sequence>
                <xs:group ref="detGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="ProcessorType">
        <xs:attribute name="type" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="CollectionType">
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
        
    <xs:element name="readouts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="readout" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="segmentation" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="name" type="xs:string"/>                                    
                                    <xs:attribute name="useForHitPosition" type="xs:boolean" use="optional" default="true" />
                                    <xs:anyAttribute processContents="lax" />
                                </xs:complexType>
                            </xs:element>                            
                            <xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1" />
                            <xs:choice minOccurs="0" maxOccurs="unbounded">
                                <xs:element name="processor" type="ProcessorType" minOccurs="0" maxOccurs="unbounded" />
                                <xs:element name="collection" type="CollectionType" />
                            </xs:choice>                                                                                                         
                        </xs:sequence>                        
                        <xs:attribute name="name" type="xs:string"/>                        
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="fields">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="field" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax" />
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="type" type="xs:string" use="required"/>
                        <xs:anyAttribute processContents="lax"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="includes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="gdmlFile" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>   
                        <xs:attribute name="ref" type="xs:anyURI" use="optional" />
                        <xs:attribute name="file" type="xs:string" use="optional" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="lccdd">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="info" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="define" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="materials" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="limits" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="regions" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="display" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="detectors" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="readouts" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="fields" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="includes" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute fixed="1.0.0" name="version" type="xs:string"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== chekanov/jas4pp/lcsim/detector-framework/src/test/resources/org/lcsim/geometry/subdetector/TPCTest.xml
<lccdd xmlns:compact="http://www.lcsim.org/schemas/compact/1.0"
       xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
       xs:noNamespaceSchemaLocation="http://www.lcsim.org/schemas/compact/1.0/compact.xsd">

  <info name="TPCTest">
  </info>

  <!-- Constants -->
  <define>

    <!-- world -->
    <constant name="world_side" value="30000" />
    <constant name="world_x" value="world_side" />
    <constant name="world_y" value="world_side" />
    <constant name="world_z" value="world_side" />

    <!-- tracking region -->
    <constant name="tracking_region_radius" value="1100.0*cm"/>
    <constant name="tracking_region_zmax" value="150.0*cm"/>
  </define>

  <materials>
  </materials>

  <detectors>
    <detector id="1" name="TPCTest" type="TPC" readout="TPCHits">
         <dimensions inner_r = "100.0*cm" outer_z = "150.0*cm" />
         <position z="500.0" /> <!-- Just a simple test of z displacement. -->
         <layer repeat="10">
           <slice material="Nitrogen" thickness="1.0*cm" sensitive="yes" />
         </layer>
    </detector>
  </detectors>

  <readouts>
    <readout name="TPCHits"> 
      <id>layer:10,system:3,barrel:3</id>
    </readout>
  </readouts>
  
  <fields>
    <field type="Solenoid" name="GlobalSolenoid"
              inner_field="5.0"
              outer_field="-0.6"
              zmax="1000"
              outer_radius="(221.0+ 5.0 + 17.5 + 40./2.)*cm"/>  <!-- SolenoidCoilBarrel inner_radius + Al support + Oxygen gap + half coil-->
   </fields>
</lccdd>

=== chekanov/jas4pp/lcsim/detector-framework/src/test/resources/org/lcsim/geometry/subdetector/LayeredSubdetectorTest.xml
<lccdd xmlns:compact="http://www.lcsim.org/schemas/compact/1.0"
       xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
       xs:noNamespaceSchemaLocation="http://www.lcsim.org/schemas/compact/1.0/compact.xsd">

  <!-- info tag containing author, version, time, unique id (url) -->
  <info name="LayeredSubdetectorTest">
    <comment>
      This is meant to test layering.  As a detector, it makes no sense.
    </comment>
  </info>

  <!-- Constants -->
  <define>
      
    <!-- world -->
    <constant name="world_side" value="15000" />
    <constant name="world_x" value="world_side" />
    <constant name="world_y" value="world_side" />
    <constant name="world_z" value="world_side" />
    
    <!-- tracking region -->
    <constant name="tracking_region_radius" value="127.0"/>
    <constant name="tracking_region_zmax" value="168.0"/>
    
    <constant name="vertex_inner_r" value="1.2"/>
    <constant name="vertex_delta_r" value="1.2"/>
    <constant name="vertex_outer_z" value="12.5"/>
    
  </define>

  <materials>

      <!-- so can easily replace references 
	   with something more realistic later -->
      <material  name="MuonAir"  >
	<D type="density" unit="g/cm3" value="0.0012"/>
	<fraction n="0.7803"  ref="N"/>
	<fraction n="0.2103"  ref="O"/>
	<fraction n="0.0094"  ref="Ar"/>
      </material>

  </materials>
 
  <detectors>
      
     <detector id="1" name="TrackerBarrelTest" type="MultiLayerTracker" readout="TkrBarrHits">
          <layer id="1" inner_r = "20.0" outer_z = "100.0">
                <slice material = "G10" thickness = "3.0" />
                <slice material = "Silicon" thickness = "2.0" sensitive = "yes" />
          </layer>
          <layer id="2" inner_r = "30" outer_z = "100.0">
                <slice material = "G10" thickness = "3.0" />
                <slice material = "Silicon" thickness = "2.0" sensitive = "yes" />
          </layer>
     </detector>
     
     <detector id="2" name="TrackerEndcapTest" type="DiskTracker" reflect="true" readout="TkrEndcapHits">
        <layer id="1" inner_r = "0.0" inner_z = "20.0" outer_r = "20.0">
                <slice material = "G10" thickness = "3.0" />
                <slice material = "Silicon" thickness = "2.0" sensitive = "yes" />
        </layer>
        <layer id="2" inner_r = "0.0" inner_z = "30.0" outer_r = "20.0">
               <slice material = "G10" thickness = "3.0" />
               <slice material = "Silicon" thickness = "2.0" sensitive = "yes" />
        </layer>       
    </detector>
    
    <detector id="3" name="CalorimeterBarrel" type="CylindricalBarrelCalorimeter" readout="HcalBarrHits">  
         <dimensions inner_r = "100.0" outer_z = "200.0" />
         <layer repeat="2" >
          <slice material = "G10" thickness = "3.0" />
          <slice material = "Silicon" thickness = "2.0" sensitive = "yes" />
        </layer>
    </detector>  

        <detector id="4" name="CalorimeterEndcapTest" reflect="true" type="CylindricalEndcapCalorimeter" readout="EcalEndcapHits">
        <dimensions inner_r = "20.0" inner_z = "200.0" outer_r = "125.0" />
        <layer repeat="2" >
          <slice material = "G10" thickness = "3.0" />
          <slice material = "Silicon" thickness = "2.0" sensitive = "yes" />
        </layer>
    </detector> 
     
  </detectors>
  <readouts>
         <readout name="MuonBarrHits"> 
             <segmentation type="ProjectiveCylinder" thetaBins="150" phiBins="300"/>
             <id>layer:7,system:3,barrel:3,theta:32:11,phi:11</id>
         </readout>
         <readout name="MuonEndcapHits"> 
             <segmentation type="ProjectiveZPlane" thetaBins="150" phiBins="300"/>
             <id>layer:7,system:3,barrel:3,theta:32:11,phi:11</id>
         </readout>
         <readout name="LumEndcapHits"> 
             <segmentation type="ProjectiveZPlane" thetaBins="600" phiBins="1200"/>
             <id>layer:7,system:3,barrel:3,theta:32:11,phi:11</id>
         </readout>
         <readout name="HcalEndcapHits"> 
             <segmentation type="ProjectiveZPlane" thetaBins="600" phiBins="1200"/>
             <id>layer:7,system:3,barrel:3,theta:32:11,phi:11</id>
         </readout>
         <readout name="HcalBarrHits"> 
             <segmentation type="ProjectiveCylinder" thetaBins="600" phiBins="1200"/>
             <id>layer:7,system:3,barrel:3,theta:32:11,phi:11</id>
         </readout>
         <readout name="EcalEndcapHits"> 
           <segmentation type="ProjectiveZPlane" thetaBins="840" phiBins="1680"/>
           <id>layer:7,system:3,barrel:3,theta:32:11,phi:11</id>
        </readout>
         <readout name="EcalBarrHits"> 
             <segmentation type="ProjectiveCylinder" thetaBins="840" phiBins="1680"/>
             <id>layer:7,system:3,barrel:3,theta:32:11,phi:11</id>
         </readout>
         <readout name="TkrBarrHits"> 
             <id>layer:10,system:3,barrel:3</id>
         </readout>
         <readout name="TkrEndcapHits"> 
             <id>layer:10,system:3,barrel:3</id>
         </readout>
         <readout name="VtxBarrHits"> 
             <id>layer:10,system:3,barrel:3</id>
         </readout>
   </readouts>
   <fields>
    <field type="Solenoid" name="GlobalSolenoid"
              inner_field="5.0"
              outer_field="-0.6"
              zmax="1000"
              outer_radius="144+(2+1)*34"/>
   </fields>
</lccdd>

=== chekanov/jas4pp/lcsim/detector-framework/src/test/resources/org/lcsim/geometry/compact/GDMLIncludeTest.xml
<lccdd xmlns:compact="http://www.lcsim.org/schemas/compact/1.0"
       xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
       xs:noNamespaceSchemaLocation="http://www.lcsim.org/schemas/compact/1.0/compact.xsd">

  <!-- info tag containing author, version, time, unique id (url) -->
  <info name="GDMLIncludeTest">
    <comment>
      Test of the compact format for sdjan03 detector.
    </comment>
  </info>

  <!-- Constants -->
  <define>
  
    <!-- world -->
    <constant name="world_side" value="15000" />
    <constant name="world_x" value="world_side" />
    <constant name="world_y" value="world_side" />
    <constant name="world_z" value="world_side" />
    
    <!-- tracking region -->
    <constant name="tracking_region_radius" value="127.0*cm"/>
    <constant name="tracking_region_zmax" value="168.0*cm"/>
        
  </define>

  <materials>

    <!-- so can easily replace references 
         with something more realistic later -->
    <material  name="MuonAir"  >
      <D type="density" unit="g/cm3" value="0.0012"/>
      <fraction n="0.7803"  ref="N"/>
      <fraction n="0.2103"  ref="O"/>
      <fraction n="0.0094"  ref="Ar"/>
    </material>
    
  </materials>
    
  <detectors>
    
    <detector id="1" name="HADBarrel" type="CylindricalBarrelCalorimeter" readout="HcalBarrHits">
      <dimensions inner_r = "144.0*cm" outer_z = "286.0*cm" />
      <layer repeat="1">
        <slice material = "Polystyrene" thickness = "1.0*cm" sensitive = "yes" />
      </layer>
      <parameter name="CALTYPE">HCAL</parameter>
    </detector>    
  </detectors>

  <readouts>
    <readout name="HcalBarrHits"> 
      <segmentation type="ProjectiveCylinder" thetaBins="600" phiBins="1200"/>
      <id>layer:7,system:3,barrel:3,theta:32:11,phi:11</id>
    </readout>
  </readouts>

  <fields>    
  </fields>

  <includes>
    <gdmlFile ref="http://www.lcsim.org/test/gdml/box.gdml" />
  </includes>

</lccdd>

=== chekanov/jas4pp/lcsim/detector-framework/src/test/resources/org/lcsim/geometry/subdetector/CylindricalEndcapCalorimeter2Test.xml
<lccdd xmlns:compact="http://www.lcsim.org/schemas/compact/1.0"
       xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
       xs:noNamespaceSchemaLocation="http://www.lcsim.org/schemas/compact/1.0/compact.xsd">

  <info name="CylindricalEndcapCalorimeter2Test"/>

  <define>
    <constant name="world_side" value="30000" />
    <constant name="world_x" value="world_side" />
    <constant name="world_y" value="world_side" />
    <constant name="world_z" value="world_side" />
    <constant name="tracking_region_radius" value="0.1*cm"/>
    <constant name="tracking_region_zmax" value="0.1*cm"/>
  </define>

  <materials>
  </materials>

  <detectors>
    <detector id="1" 
              name="EMEndcap" 
              type="CylindricalEndcapCalorimeter2" 
              readout="EcalEndcapHits">
        <dimensions rmin="200.0" zmin="300.0" rmax="1250.0" angle="10.0*deg" />
        <layer repeat="5" >
          <slice material="Silicon" thickness="20.0" sensitive="yes" />
          <slice material="Tungsten" thickness="80.0" />
        </layer>
    </detector>
  </detectors>

  <readouts>
         <readout name="EcalEndcapHits">
             <segmentation type="GridXYZ" gridSizeX="10.0" gridSizeY="10.0"/>
             <id>system:3,barrel:3,layer:7,x:32:-16,y:-16</id>
         </readout>
   </readouts>

</lccdd>

=== chekanov/jas4pp/lcsim/detector-framework/src/test/resources/org/lcsim/geometry/subdetector/PolyhedraBarrelCalorimeter2Test.xml
<lccdd xmlns:compact="http://www.lcsim.org/schemas/compact/1.0"
       xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
       xs:noNamespaceSchemaLocation="http://www.lcsim.org/schemas/compact/1.0/compact.xsd">

  <info name="PolyhedraBarrelCalorimeterTest">
    <comment>Test of org.lcsim.geometry.subdetector.PolyhedraBarrelCalorimeter class.</comment>
  </info>

  <!-- Constants -->
  <define>

    <!-- world -->
    <constant name="world_side" value="30000" />
    <constant name="world_x" value="world_side" />
    <constant name="world_y" value="world_side" />
    <constant name="world_z" value="world_side" />

    <!-- tracking region -->
    <constant name="tracking_region_radius" value="0.1*cm"/>
    <constant name="tracking_region_zmax" value="0.1*cm"/>
  </define>

  <materials>
  </materials>

  <detectors>
    <detector id="7" name="HcalBarrel" type="PolyhedraBarrelCalorimeter2" readout="HcalBarrelHits" calorimeterType="HAD_BARREL" gap="2.*cm" material="Steel235">
            <comment>Hadron Calorimeter Barrel</comment>
            <dimensions numsides="12" rmin="1404.0" z="3688.0 * 2"/>
            <layer repeat="60">
                <slice material = "Steel235" thickness = "1.89*cm" />
                <slice material = "PyrexGlass" thickness = "0.11*cm" />
                <slice material = "RPCGasDefault" thickness = "0.12*cm" sensitive = "yes" />
                <slice material = "PyrexGlass" thickness = "0.11*cm" />
                <slice material = "G10" thickness = "0.3*cm" />
                <slice material = "Air" thickness = "0.16*cm" />
            </layer>
  </detector>
  </detectors>

  <readouts>
    <readout name="HcalBarrelHits">
            <segmentation type="CartesianGridXY" gridSizeX="1.0*cm" gridSizeY="1.0*cm" />
            <id>system:6,barrel:3,module:4,layer:8,slice:5,x:32:-16,y:-16</id>
        </readout>
  </readouts>

  <fields>
  </fields>
</lccdd>
