=== chekanov/jas4pp/lcsim/detector-framework/src/main/resources/org/lcsim/schemas/compact/1.0/compact.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE  xs:schema >
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="unqualified"
           version="1.0"
           xmlns:compact="http://www.lcsim.org/schemas/compact/1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="info">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="comment" type="xs:string" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="title" type="xs:string" use="optional" />
            <xs:attribute name="author" type="xs:string" use="optional" />
            <xs:attribute name="url" type="xs:anyURI" use="optional"/>
            <xs:attribute name="version" type="xs:string" use="optional" />
            <xs:attribute name="status" default="development">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="deprecated" />
                        <xs:enumeration value="production" />
                        <xs:enumeration value="development" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="define">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="constant" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attribute name="name" type="xs:string" use="required"/>
                            <xs:attribute name="value" type="xs:string" use="required"/>
                        </xs:complexType>                    
                    </xs:element>
                    <xs:element name="matrix" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attribute name="name" type="xs:string" use="required" />
                            <xs:attribute name="coldim" type="xs:integer" use="required" />
                            <xs:attribute name="values" type="xs:string" use="required" />
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="limits">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="limitset" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="limit" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="name" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="step_length_max" />
                                                <xs:enumeration value="track_length_max" />
                                                <xs:enumeration value="time_max" />
                                                <xs:enumeration value="ekin_min" />
                                                <xs:enumeration value="range_min" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="particles" type="xs:string"/>
                                    <xs:attribute name="value" type="xs:double"/>
                                    <xs:attribute name="unit" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="regions">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="region" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="storeSecondaries" type="xs:boolean" default="false"/>
                        <xs:attribute name="killTracks" type="xs:boolean" default="false"/>
                        <xs:attribute name="cut" type="xs:double" default="1.0" />
                        <xs:attribute name="lunit" type="xs:string" default="mm"/>
                        <xs:attribute name="threshold" type="xs:double" default="0.0"/>
                        <xs:attribute name="eunit" type="xs:string" default="MeV"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="materials">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="material" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="property" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="name" type="xs:string" use="required" />
                                    <xs:attribute name="ref" type="xs:string" use="required" />
                                </xs:complexType>
                            </xs:element>                            
                            <xs:element name="D" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="type" type="xs:string" default="density"/>
                                    <xs:attribute name="unit" type="xs:string" default="g/cm3" />
                                    <xs:attribute name="value" type="xs:double" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:choice>
                                <xs:element name="fraction" minOccurs="1" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:attribute name="n" type="xs:double" use="required"/>
                                        <xs:attribute name="ref" type="xs:string" use="required"/>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="composite" minOccurs="1" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:attribute name="n" type="xs:integer" use="required"/>
                                        <xs:attribute name="ref" type="xs:string" use="required"/>
                                    </xs:complexType>
                                </xs:element>
                            </xs:choice>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="display">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="vis" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required" />
                        <xs:attribute name="r" type=" xs:double " default="1.0" />
                        <xs:attribute name="g" type=" xs:double " default="1.0" />
                        <xs:attribute name="b" type=" xs:double " default="1.0" />
                        <xs:attribute name="alpha" type=" xs:double " default="1.0" />
                        <xs:attribute name="visible" type="xs:boolean" default="true"/>
                        <xs:attribute name="showDaughters" type="xs:boolean" default="true"/>
                        <xs:attribute name="lineStyle" default="unbroken">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="unbroken"/>
                                    <xs:enumeration value="dashed"/>
                                    <xs:enumeration value="dotted"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="drawingStyle" default="wireframe">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="wireframe"/>
                                    <xs:enumeration value="solid"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="detector">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="comment" minOccurs="0" maxOccurs="1" type="xs:string"/>
                <xs:element name="dimensions" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:anyAttribute processContents="lax" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="layer" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="slice" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="material" type="xs:string" use="required"/>
                                    <xs:attribute name="thickness" type="xs:string" use="required"/>
                                    <xs:attribute name="sensitive" default="no">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="yes" />
                                                <xs:enumeration value="no" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="region" type="xs:string" use="optional"/>
                                    <xs:attribute name="limits" type="xs:string" use="optional"/>
                                    <xs:attribute name="vis" type="xs:string" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
                        </xs:sequence>
                        <xs:anyAttribute processContents="lax"/> <!-- layer -->
                    </xs:complexType>
                </xs:element>
                <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax" />
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="type" type="xs:string" use="required"/>
            <xs:attribute name="id" type="xs:integer" use="optional" default="0"/>
            <xs:attribute name="readout" type="xs:string" use="optional" />
            <xs:attribute name="insideTrackingVolume" type="xs:boolean" use="optional" />
            <xs:attribute name="reflect" type="xs:boolean" use="optional"/>
            <xs:attribute name="combineHits" type="xs:boolean" use="optional"/>
            <xs:attribute name="calorimeterType" type="xs:string" use="optional"/>
            <xs:anyAttribute processContents="lax"/>
        </xs:complexType>
    </xs:element>                

    <xs:group name="detGroup">
        <xs:sequence>
            <xs:element name="comment" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
            <xs:element ref="detector" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:group>
    
    <xs:element name="detectors">
        <xs:complexType>
            <xs:sequence>
                <xs:group ref="detGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="ProcessorType">
        <xs:attribute name="type" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="CollectionType">
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
        
    <xs:element name="readouts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="readout" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="segmentation" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="name" type="xs:string"/>                                    
                                    <xs:attribute name="useForHitPosition" type="xs:boolean" use="optional" default="true" />
                                    <xs:anyAttribute processContents="lax" />
                                </xs:complexType>
                            </xs:element>                            
                            <xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1" />
                            <xs:choice minOccurs="0" maxOccurs="unbounded">
                                <xs:element name="processor" type="ProcessorType" minOccurs="0" maxOccurs="unbounded" />
                                <xs:element name="collection" type="CollectionType" />
                            </xs:choice>                                                                                                         
                        </xs:sequence>                        
                        <xs:attribute name="name" type="xs:string"/>                        
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="fields">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="field" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax" />
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="type" type="xs:string" use="required"/>
                        <xs:anyAttribute processContents="lax"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="includes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="gdmlFile" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>   
                        <xs:attribute name="ref" type="xs:anyURI" use="optional" />
                        <xs:attribute name="file" type="xs:string" use="optional" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="lccdd">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="info" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="define" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="materials" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="limits" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="regions" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="display" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="detectors" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="readouts" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="fields" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="includes" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute fixed="1.0.0" name="version" type="xs:string"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== chekanov/jas4pp/lcsim/detector-data/detectors/sidEcalTestbeam/compact.xml
<lccdd xmlns:compact="http://www.lcsim.org/schemas/compact/1.0"
       xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
       xs:noNamespaceSchemaLocation="http://www.lcsim.org/schemas/compact/1.0/compact.xsd">

  <info name="sidEcalTestbeam">
    <comment>SiD ECal Test beam module 2014.01.15 Norman Graf</comment>
  </info>

  <define>

    <constant name="cm" value="10"/>

    <!-- world -->
    <constant name="world_side" value="3000*cm" />
    <constant name="world_x" value="world_side" />
    <constant name="world_y" value="world_side" />
    <constant name="world_z" value="world_side" />

    <!-- tracking region -->
    <constant name="tracking_region_radius" value="150.0*cm"/>
    <constant name="tracking_region_zmax" value="200.0*cm"/>

  </define>

  <materials>
        <material name="TungstenDens23">
            <D value="17.66" unit="g/cm3"/>
            <fraction n="0.925" ref="W"/>
            <fraction n="0.050" ref="Ni"/>
            <fraction n="0.025" ref="Cu"/>
        </material>
  </materials>

    <limits>
        <limitset name="cal_limits">
            <limit name="step_length_max" particles="*" value="3.5" unit="mm" />
        </limitset>
    </limits>

  <detectors>

    <detector id="1"
              name="SiDTestBeamCalorimeter"
              type="TestBeamCalorimeter"
              readout="CalHits"
              insideTrackingVolume="true">
             <dimensions x="6.0 * cm" y="6.0 * cm" />
             <position x="0.0 * cm" y="0.0 * cm" z="10.0*cm" />
             <layer repeat="1">
                <slice material = "Kapton"  thickness = "0.030*cm" />
                <slice material = "Copper"  thickness = "0.005*cm" />                
                <slice material = "Silicon" thickness = "0.032*cm" sensitive = "yes" limits="cal_limits" />                
            </layer>
            <layer repeat="20">
                <slice material = "TungstenDens23" thickness = "0.254*cm" />
                <slice material = "Air"     thickness = "0.098*cm" />
                <slice material = "Kapton"  thickness = "0.030*cm" />
                <slice material = "Copper"  thickness = "0.005*cm" />
                <slice material = "Silicon" thickness = "0.032*cm" sensitive = "yes" limits="cal_limits" />
            </layer>
            <layer repeat="10">
                <slice material = "TungstenDens23" thickness = "0.508*cm" />
                <slice material = "Air"     thickness = "0.098*cm" />
                <slice material = "Kapton"  thickness = "0.030*cm" />
                <slice material = "Copper"  thickness = "0.005*cm" />
                <slice material = "Silicon" thickness = "0.032*cm" sensitive = "yes" limits="cal_limits" />
            </layer>
    </detector>
  </detectors>

  <readouts>
        <readout name="CalHits">
            <segmentation type="GlobalGridXY" gridSizeX="3.5" gridSizeY="3.5" />
            <id>system:6,barrel:3,module:4,layer:6,slice:5,x:32:-16,y:-16</id>
        </readout>
   </readouts>
    <fields/>
</lccdd>

=== chekanov/jas4pp/lcsim/detector-framework/src/test/resources/org/lcsim/geometry/subdetector/SiDHcalTest.xml
<lccdd xmlns:compact="http://www.lcsim.org/schemas/compact/1.0"
       xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
       xs:noNamespaceSchemaLocation="http://www.lcsim.org/schemas/compact/1.0/compact.xsd">

  <info name="SiDHcalTest">
    <comment>Test of org.lcsim.geometry.subdetector.PolyhedraBarrelCalorimeter class.</comment>
  </info>

  <!-- Constants -->
  <define>

    <!-- world -->
    <constant name="world_side" value="30000" />
    <constant name="world_x" value="world_side" />
    <constant name="world_y" value="world_side" />
    <constant name="world_z" value="world_side" />

    <!-- tracking region -->
    <constant name="tracking_region_radius" value="0.1*cm"/>
    <constant name="tracking_region_zmax" value="0.1*cm"/>
  </define>

  <materials>
  </materials>

  <detectors>
    <detector id="1"
              name="HcalTest"
              type="SidHcal"
              readout="CalHits"> 
         <dimensions numsides="12" z="1000.0" rmin="2834.0/2.0" gap="50.0"/>
         <layer repeat="1">
<!--           <slice material="Silicon" thickness="5.0" sensitive="yes" />-->
           <slice material="Tungsten" thickness="1166.0" sensitive="yes" />
         </layer>
    </detector>
  </detectors>

  <readouts>
    <readout name="CalHits">
      <segmentation type="GridXYZ" gridSizeX="1.0" gridSizeY="1.0" />
      <id>system:6,barrel:3,module:5,layer:8,slice:5,x:32:-10,y:-10</id>
    </readout>
  </readouts>

  <fields>
  </fields>
</lccdd>

=== chekanov/jas4pp/lcsim/detector-framework/src/test/resources/org/lcsim/detector/converter/compact/PolyhedraEndcapCalorimeter2Test.xml
<lccdd xmlns:compact="http://www.lcsim.org/schemas/compact/1.0"
       xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
       xs:noNamespaceSchemaLocation="http://www.lcsim.org/schemas/compact/1.0/compact.xsd">
    <info name="PolyhedraEndcapCalorimeter2Test"/>
    <define>       
        <constant name="world_side" value="30000" />
        <constant name="world_x" value="world_side" />
        <constant name="world_y" value="world_side" />
        <constant name="world_z" value="world_side" />
        <constant name="tracking_region_radius" value="0.1*cm"/>
        <constant name="tracking_region_zmax" value="0.1*cm"/>
    </define>
    <materials/>
    <detectors>
        <detector id="6" name="TestEndcap" type="PolyhedraEndcapCalorimeter2" reflect="true" readout="HcalEndcapHits">
            <dimensions numsides="8" zmin="1000.0" rmin="200.0" rmax="1200.0" />
            <layer repeat="2">
                <slice material = "Silicon" thickness = "10.0" sensitive = "yes" />
                <slice material = "Copper"  thickness = "50.0" />
            </layer>  
            <layer repeat="1">
                <slice material = "Copper"  thickness = "100.0" />
            </layer>
        </detector>
    </detectors>
    <readouts>
        <readout name="HcalEndcapHits">
            <segmentation type="CartesianGridXY" gridSizeX="1.0*cm" gridSizeY="1.0*cm" />
            <id>system:6,barrel:3,layer:6,slice:5,x:32:-16,y:-16</id>
        </readout>
    </readouts>
</lccdd>

=== chekanov/jas4pp/lcsim/detector-framework/src/test/resources/org/lcsim/geometry/compact/npcyl.xml
<lccdd xmlns:compact="http://www.lcsim.org/schemas/compact/1.0"
       xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
       xs:noNamespaceSchemaLocation="http://www.lcsim.org/schemas/compact/1.0/compact.xsd">

  <!-- info tag containing author, version, time, unique id (url) -->
  <info name="Detector">
    <comment>
      Compact format template file.
    </comment>
  </info>

  <!-- Constants -->
  <define>
  
    <!-- world -->
    <constant name="world_side" value="15000" />
    <constant name="world_x" value="world_side" />
    <constant name="world_y" value="world_side" />
    <constant name="world_z" value="world_side" />
    
    <!-- tracking region -->
    <constant name="tracking_region_radius" value="127.0*cm"/>
    <constant name="tracking_region_zmax" value="168.0*cm"/>    
    
  </define>

  <materials>

      <!-- elements -->
      <element name="Ar" Z="18.0" N="40" >
	<atom type="A" unit="g/mol" value="39.9480" />
      </element>

      <element  name="N"  Z="7.0"  N="14" >
	<atom type="A" unit="g/mol" value=" 14.0100" />
      </element>

      <element  name="O"  Z="8.0"  N="16" >
	<atom type="A" unit="g/mol" value=" 16.0000" />
      </element>

      <!-- materials -->
      <material  name="Air"  >
	<D type="density" unit="g/cm3" value="0.0012"/>
	<fraction n="0.7803"  ref="N"/>
	<fraction n="0.2103"  ref="O"/>
	<fraction n="0.0094"  ref="Ar"/>
      </material>
      
  </materials>
  
  <detectors>    
    <detector id="0" name="NPCylTestDet" type="CylindricalCalorimeter" readout="NPCylTest" detectorType="calorimeter">
      <dimensions inner_r="100.0 * cm" outer_z="200.0 * cm" />
      <layer repeat="1">
	<slice material="Air" thickness="100.0 * cm" sensitive="yes" />
      </layer>
    </detector>
  </detectors>

  <readouts>
    <readout name="NPCylTest">
      <segmentation type="NonprojectiveCylinder" gridSizePhi="1.0" gridSizeZ="1.0"/>
      <id>layer:7,system:3,barrel:3,phi:32:11,z:11</id>
    </readout>
  </readouts>
  
  <fields>
    <field type="Solenoid" name="GlobalSolenoid"
	   inner_field="5.0"
	   outer_field="-0.6"
	   zmax="1000"
	   outer_radius="144*cm+(2+1)*34*cm" />
  </fields>
</lccdd>

=== chekanov/jas4pp/lcsim/detector-framework/src/test/resources/org/lcsim/geometry/subdetector/TubeSegmentTest.xml
<lccdd xmlns:compact="http://www.lcsim.org/schemas/compact/1.0"
       xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
       xs:noNamespaceSchemaLocation="http://www.lcsim.org/schemas/compact/1.0/compact.xsd">

    <info name="TubeSegmentTest">
        <comment>Test of TubeSegment subdetector type.</comment>
    </info>

    <define>    
        <constant name="world_side" value="30000" />
        <constant name="world_x" value="world_side" />
        <constant name="world_y" value="world_side" />
        <constant name="world_z" value="world_side" />
        <constant name="tracking_region_radius" value="0.1*cm"/>
        <constant name="tracking_region_zmax" value="0.1*cm"/>
    </define>

    <materials>
    </materials>

    <display>
        <vis name="Red" r="1.0" g="0.0" b="0.0" />
    </display>

    <detectors>
      <detector id="1" name="TubeSegment" type="TubeSegment" vis="Red">
    	  <material name="Air"/>
    	  <tubs rmin="10.0" rmax="50.0" zhalf="50.0"/>
    	  <position x="0.0" y="0.0" z="200.0"/>
    	  <rotation x="0.0" y="0.2" z="0."/>
      </detector>
    </detectors>

    <readouts>
    </readouts>
    
    <fields>
   </fields>
   
</lccdd>
