=== chekanov/jas4pp/lcsim/detector-framework/src/main/resources/org/lcsim/schemas/compact/1.0/compact.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE  xs:schema >
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="unqualified"
           version="1.0"
           xmlns:compact="http://www.lcsim.org/schemas/compact/1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="info">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="comment" type="xs:string" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="title" type="xs:string" use="optional" />
            <xs:attribute name="author" type="xs:string" use="optional" />
            <xs:attribute name="url" type="xs:anyURI" use="optional"/>
            <xs:attribute name="version" type="xs:string" use="optional" />
            <xs:attribute name="status" default="development">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="deprecated" />
                        <xs:enumeration value="production" />
                        <xs:enumeration value="development" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="define">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="constant" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attribute name="name" type="xs:string" use="required"/>
                            <xs:attribute name="value" type="xs:string" use="required"/>
                        </xs:complexType>                    
                    </xs:element>
                    <xs:element name="matrix" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attribute name="name" type="xs:string" use="required" />
                            <xs:attribute name="coldim" type="xs:integer" use="required" />
                            <xs:attribute name="values" type="xs:string" use="required" />
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="limits">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="limitset" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="limit" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="name" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="step_length_max" />
                                                <xs:enumeration value="track_length_max" />
                                                <xs:enumeration value="time_max" />
                                                <xs:enumeration value="ekin_min" />
                                                <xs:enumeration value="range_min" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="particles" type="xs:string"/>
                                    <xs:attribute name="value" type="xs:double"/>
                                    <xs:attribute name="unit" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="regions">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="region" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="storeSecondaries" type="xs:boolean" default="false"/>
                        <xs:attribute name="killTracks" type="xs:boolean" default="false"/>
                        <xs:attribute name="cut" type="xs:double" default="1.0" />
                        <xs:attribute name="lunit" type="xs:string" default="mm"/>
                        <xs:attribute name="threshold" type="xs:double" default="0.0"/>
                        <xs:attribute name="eunit" type="xs:string" default="MeV"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="materials">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="material" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="property" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="name" type="xs:string" use="required" />
                                    <xs:attribute name="ref" type="xs:string" use="required" />
                                </xs:complexType>
                            </xs:element>                            
                            <xs:element name="D" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="type" type="xs:string" default="density"/>
                                    <xs:attribute name="unit" type="xs:string" default="g/cm3" />
                                    <xs:attribute name="value" type="xs:double" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:choice>
                                <xs:element name="fraction" minOccurs="1" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:attribute name="n" type="xs:double" use="required"/>
                                        <xs:attribute name="ref" type="xs:string" use="required"/>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="composite" minOccurs="1" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:attribute name="n" type="xs:integer" use="required"/>
                                        <xs:attribute name="ref" type="xs:string" use="required"/>
                                    </xs:complexType>
                                </xs:element>
                            </xs:choice>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="display">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="vis" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required" />
                        <xs:attribute name="r" type=" xs:double " default="1.0" />
                        <xs:attribute name="g" type=" xs:double " default="1.0" />
                        <xs:attribute name="b" type=" xs:double " default="1.0" />
                        <xs:attribute name="alpha" type=" xs:double " default="1.0" />
                        <xs:attribute name="visible" type="xs:boolean" default="true"/>
                        <xs:attribute name="showDaughters" type="xs:boolean" default="true"/>
                        <xs:attribute name="lineStyle" default="unbroken">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="unbroken"/>
                                    <xs:enumeration value="dashed"/>
                                    <xs:enumeration value="dotted"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="drawingStyle" default="wireframe">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="wireframe"/>
                                    <xs:enumeration value="solid"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="detector">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="comment" minOccurs="0" maxOccurs="1" type="xs:string"/>
                <xs:element name="dimensions" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:anyAttribute processContents="lax" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="layer" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="slice" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="material" type="xs:string" use="required"/>
                                    <xs:attribute name="thickness" type="xs:string" use="required"/>
                                    <xs:attribute name="sensitive" default="no">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="yes" />
                                                <xs:enumeration value="no" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="region" type="xs:string" use="optional"/>
                                    <xs:attribute name="limits" type="xs:string" use="optional"/>
                                    <xs:attribute name="vis" type="xs:string" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
                        </xs:sequence>
                        <xs:anyAttribute processContents="lax"/> <!-- layer -->
                    </xs:complexType>
                </xs:element>
                <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax" />
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="type" type="xs:string" use="required"/>
            <xs:attribute name="id" type="xs:integer" use="optional" default="0"/>
            <xs:attribute name="readout" type="xs:string" use="optional" />
            <xs:attribute name="insideTrackingVolume" type="xs:boolean" use="optional" />
            <xs:attribute name="reflect" type="xs:boolean" use="optional"/>
            <xs:attribute name="combineHits" type="xs:boolean" use="optional"/>
            <xs:attribute name="calorimeterType" type="xs:string" use="optional"/>
            <xs:anyAttribute processContents="lax"/>
        </xs:complexType>
    </xs:element>                

    <xs:group name="detGroup">
        <xs:sequence>
            <xs:element name="comment" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
            <xs:element ref="detector" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:group>
    
    <xs:element name="detectors">
        <xs:complexType>
            <xs:sequence>
                <xs:group ref="detGroup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="ProcessorType">
        <xs:attribute name="type" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="CollectionType">
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
        
    <xs:element name="readouts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="readout" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="segmentation" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="name" type="xs:string"/>                                    
                                    <xs:attribute name="useForHitPosition" type="xs:boolean" use="optional" default="true" />
                                    <xs:anyAttribute processContents="lax" />
                                </xs:complexType>
                            </xs:element>                            
                            <xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1" />
                            <xs:choice minOccurs="0" maxOccurs="unbounded">
                                <xs:element name="processor" type="ProcessorType" minOccurs="0" maxOccurs="unbounded" />
                                <xs:element name="collection" type="CollectionType" />
                            </xs:choice>                                                                                                         
                        </xs:sequence>                        
                        <xs:attribute name="name" type="xs:string"/>                        
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="fields">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="field" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax" />
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="type" type="xs:string" use="required"/>
                        <xs:anyAttribute processContents="lax"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="includes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="gdmlFile" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>   
                        <xs:attribute name="ref" type="xs:anyURI" use="optional" />
                        <xs:attribute name="file" type="xs:string" use="optional" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="lccdd">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="info" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="define" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="materials" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="limits" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="regions" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="display" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="detectors" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="readouts" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="fields" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="includes" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute fixed="1.0.0" name="version" type="xs:string"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== chekanov/jas4pp/lcsim/detector-framework/src/test/resources/org/lcsim/geometry/subdetector/OpticalCalorimeterTest.xml
<lccdd xmlns:compact="http://www.lcsim.org/schemas/compact/1.0"
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.lcsim.org/schemas/compact/1.0/compact.xsd">

    <info name="OpticalCalorimeterTest"/>

    <define>
        <constant name="world_side" value="30000" />
        <constant name="world_x" value="world_side" />
        <constant name="world_y" value="world_side" />
        <constant name="world_z" value="world_side" />
        <constant name="tracking_region_radius" value="125.0*cm"/>
        <constant name="tracking_region_zmax" value="200.0*cm"/>
        <matrix name="prop1" coldim="2"  values="0.000002034 1.65
                                                0.000002068 1.65
                                                0.000002103 1.65 
                                                0.000002139 1.65
                                                0.000002177 1.65
                                                0.000002216 1.65
                                                0.000002256 1.65
                                                0.000002298 1.65
                                                0.000002341 1.65
                                                0.000002386 1.65 
                                                0.000002433 1.65
                                                0.000002481 1.65
                                                0.000002532 1.65
                                                0.000002585 1.65
                                                0.000002640 1.65
                                                0.000002697 1.65
                                                0.000002757 1.65
                                                0.000002820 1.65
                                                0.000002885 1.65
                                                0.000002954 1.65
                                                0.000003026 1.65
                                                0.000003102 1.65
                                                0.000003181 1.65
                                                0.000003265 1.65
                                                0.000003353 1.65
                                                0.000003446 1.65
                                                0.000003545 1.65
                                                0.000003649 1.65
                                                0.000003760 1.65
                                                0.000003877 1.65 
                                                0.000004002 1.65
                                                0.000004136 1.65"/>
    </define>
    <materials>
        <material name="BGO">
            <property name="RINDEX" ref="prop1" />
            <D value="7.13" unit="g/cm3"/>
            <composite n="4" ref="Bi"/>
            <composite n="3" ref="Ge"/>
            <composite n="12" ref="O"/>
        </material>
    </materials>
    <limits>
        <limitset name="cal_limits">
            <limit name="step_length_max" particles="*" value="5.0" unit="mm" />
        </limitset>
    </limits>
    <detectors>
        <detector id="7" 
                  name="HcalBarrel" 
                  type="PolyhedraBarrelCalorimeter2" 
                  readout="HcalBarrelHits" 
                  calorimeterType="HAD_BARREL" 
                  gap="0.*cm" 
                  material="BGO"
                  optical="true">
            <comment>Hadron Calorimeter Barrel</comment>
            <dimensions numsides="12" rmin="146*cm" z="370.2*cm * 2"/>
            <staves />
            <layer repeat="30">
                <slice material="BGO" thickness="5.0*cm" sensitive="yes" />
            </layer>
        </detector>
        <detector id="8" 
                  name="HcalEndcap" 
                  type="PolyhedraEndcapCalorimeter3" 
                  readout="HcalEndcapHits" 
                  reflect="true" 
                  calorimeterType="HAD_ENDCAP">
            <comment>Hadron Calorimeter Endcaps</comment>
            <dimensions numsides="12" zmin="220.2*cm" rmin="39.0*cm" rmax="146.0*cm" angle="6.*deg" />
            <layer repeat="30">
                <slice material="BGO" thickness="5.0*cm" sensitive="yes" />
            </layer>
        </detector>
    </detectors>
    <readouts>
        <readout name="HcalBarrelHits">
            <segmentation type="CartesianGridXY" gridSizeX="2.0*cm" gridSizeY="2.0*cm" />
            <id>system:6,barrel:3,module:4,layer:6,slice:5,x:32:-16,y:-16</id>
        </readout>
        <readout name="HcalEndcapHits">
            <segmentation type="GlobalGridXY" gridSizeX="2.0*cm" gridSizeY="2.0*cm" />
            <id>system:6,barrel:3,module:4,layer:8,slice:5,x:32:-16,y:-16</id>
        </readout>
    </readouts>
    <fields>
        <field type="Solenoid" name="GlobalSolenoid"
        inner_field="5.0"
        outer_field="-0.6"
        zmax="1000*cm"
        outer_radius="300*cm"/>
    </fields>
</lccdd>

=== chekanov/jas4pp/lcsim/detector-framework/src/test/resources/org/lcsim/geometry/subdetector/PolyhedraEndcapCalorimeter3Test.xml
<lccdd xmlns:compact="http://www.lcsim.org/schemas/compact/1.0"
       xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
       xs:noNamespaceSchemaLocation="http://www.lcsim.org/schemas/compact/1.0/compact.xsd">

  <info name="PolyhedraEndcapCalorimeter3Test"/>

  <define>    

    <constant name="world_side" value="30000" />
    <constant name="world_x" value="world_side" />
    <constant name="world_y" value="world_side" />
    <constant name="world_z" value="world_side" />

    <constant name="tracking_region_radius" value="499.0"/>
    <constant name="tracking_region_zmax" value="999.0"/>
  </define>

  <materials/>

  <detectors>
    <detector id="1" 
              name="PolyhedraEndcapCalorimeterTest" 
              type="PolyhedraEndcapCalorimeter3" 
              readout="CalHits"
              reflect="true">
         <dimensions numsides="4" zmin="50.0" rmin="500.0" rmax="1000.0" angle="10.*deg" />
         <layer repeat="30">
           <slice material="Silicon" thickness="10.0" sensitive="yes" />
           <slice material="Tungsten" thickness="40.0" sensitive="no" vis="AbsorberVis" />
         </layer>
    </detector>
  </detectors>

  <readouts>
    <readout name="CalHits">
      <segmentation type="GlobalGridXY" gridSizeX="1.0" gridSizeY="1.0" />
      <id>layer:8,system:6,barrel:3,slice:4,x:32:-16,y:-16</id>
    </readout>
  </readouts>
</lccdd>

=== chekanov/jas4pp/lcsim/detector-framework/src/test/resources/org/lcsim/geometry/subdetector/EcalBarrelTest.xml
<lccdd xmlns:compact="http://www.lcsim.org/schemas/compact/1.0"
       xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
       xs:noNamespaceSchemaLocation="http://www.lcsim.org/schemas/compact/1.0/compact.xsd">

  <info name="EcalBarrelTest">
  </info>

  <define>

    <!-- world -->
    <constant name="world_side" value="15000" />
    <constant name="world_x" value="world_side" />
    <constant name="world_y" value="world_side" />
    <constant name="world_z" value="world_side" />

    <!-- tracking region -->
    <constant name="tracking_region_radius" value="127.0"/>
    <constant name="tracking_region_zmax" value="168.0"/>
    
  </define>

  <materials>
  </materials>

  <display>
    <vis name="DetectorVis" r="0.77" g="0.74" b="0.86" showDaughters="true" visible="true"/>
    <vis name="StaveVis" r="0.77" g="0.74" b="0.86" showDaughters="false" visible="true"/>
    <vis name="LayerVis" r="1.0" g="0.0" b="0.0" showDaughters="true" visible="false"/>
    <vis name="SensorVis" r="0.0" g="1.0" b="0.0" showDaughters="false" visible="true"/>
    <vis name="AbsorberVis" r="0.0" g="0.0" b="1.0" showDaughters="false" visible="true"/>
  </display>

  <detectors>
    <detector id="1" name="EcalBarrel" type="EcalBarrel" readout="EcalBarrHits" vis="DetectorVis">
      <dimensions numsides="8" rmin="1700.0" z="546.0 * 2" />
      <staves vis="StaveVis"/>
      <layer repeat="8" vis="LayerVis">
        <slice material="Silicon" thickness="10.0" sensitive="yes" vis="SensorVis"/>
<!--        <slice material="Air" thickness="2.0" sensitive="yes" vis="InvisibleNoDaughters"/>-->
        <slice material="Lead" thickness="20.0" sensitive="yes" vis="AbsorberVis"/>
      </layer>
    </detector>
  </detectors>

  <readouts>
         <readout name="EcalBarrHits">
             <segmentation type="GridXYZ" gridSizeX="1.0" gridSizeY="1.0" />
	     <id>layer:8,system:6,barrel:3,module:4,slice:6,x:32:-15,y:-15</id>
         </readout>
   </readouts>

   <fields>
   </fields>
</lccdd>

=== chekanov/jas4pp/lcsim/detector-framework/src/test/resources/org/lcsim/geometry/subdetector/CylindricalCalorimeterTest.xml
<lccdd xmlns:compact="http://www.lcsim.org/schemas/compact/1.0"
       xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
       xs:noNamespaceSchemaLocation="http://www.lcsim.org/schemas/compact/1.0/compact.xsd">

  <info name="sidmay05">
    <comment>The compact format for sidmay05 detector.</comment>
  </info>

  <!-- Constants -->
  <define>

    <!-- world -->
    <constant name="world_side" value="30000" />
    <constant name="world_x" value="world_side" />
    <constant name="world_y" value="world_side" />
    <constant name="world_z" value="world_side" />

    <!-- tracking region -->
    <constant name="tracking_region_radius" value="0.1*cm"/>
    <constant name="tracking_region_zmax" value="0.1*cm"/>

  </define>

  <materials>
  </materials>

  <detectors>

<!-- Electromagnetic calorimeter -->

    <detector id="1" name="EMBarrel" type="CylindricalBarrelCalorimeter" readout="EcalBarrHits">
         <dimensions inner_r = "127.0*cm" outer_z = "179.5*cm" />
         <layer repeat="30">
           <slice material = "Tungsten" thickness = "0.25*cm" />
           <slice material = "Nitrogen" thickness = "0.068*cm" />
           <slice material = "Silicon" thickness = "0.032*cm" sensitive = "yes" />
           <slice material = "Oxygen" thickness = "0.025*cm" />
         </layer>
    </detector>

    <detector id="2" name="EMEndcap" reflect="true" type="CylindricalEndcapCalorimeter" readout="EcalEndcapHits">
        <dimensions inner_r = "20.0*cm" inner_z = "168.0*cm" outer_r = "125.0*cm" />
        <layer repeat="30" >
          <slice material = "Tungsten" thickness = "0.25*cm" />
          <slice material = "Nitrogen" thickness = "0.068*cm" />
          <slice material = "Silicon" thickness = "0.032*cm" sensitive = "yes" />
          <slice material = "Oxygen" thickness = "0.025*cm" />
        </layer>
    </detector>
  </detectors>

<!-- Sensitive Detector readout segmentation -->
  <readouts>
         <readout name="EcalEndcapHits">
           <segmentation type="ProjectiveZPlane" thetaBins="1024" phiBins="1024"/>
           <id>layer:7,system:3,barrel:3,theta:32:11,phi:11</id>
        </readout>
         <readout name="EcalBarrHits">
             <segmentation type="ProjectiveCylinder" thetaBins="1000" phiBins="2000"/>
             <id>layer:7,system:3,barrel:3,theta:32:11,phi:11</id>
         </readout>
   </readouts>
    <fields>
    <field type="Solenoid" name="GlobalSolenoid"
              inner_field="5.0"
              outer_field="-0.6"
              zmax="1000"
              outer_radius="(221.0+ 5.0 + 17.5 + 40./2.)*cm"/>  <!-- SolenoidCoilBarrel inner_radius + Al support + Oxygen gap + half coil-->
   </fields>
</lccdd>
